import Link from "next/link";
import { CalendarDays, CheckCircle2, CircleAlert, FileText, Link2, Megaphone, Radio, Send, Settings2, Users } from "lucide-react";
import { ActionForm } from "@/components/ActionForm";
import { CommunicationsCalendar, type CommunicationCalendarEvent } from "@/components/CommunicationsCalendar";
import { PageHeader } from "@/components/PageHeader";
import { approveCampaignAction, cancelCampaignAction, createAudienceAction, createCampaignAction, createCommunicationTemplateAction, disconnectSocialConnectionAction, saveCommunicationConsentAction, saveSocialConnectionAction, scheduleCampaignAction, submitWhatsAppTemplateAction, syncWhatsAppTemplateAction, updateCampaignContentAction } from "@/lib/communication-actions";
import { requirePermission } from "@/lib/auth";
import { canAccess } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { stringList } from "@/lib/database-compat";
import type { CommunicationChannel } from "@prisma/client";

const views = [
  ["calendar", "Calendario", CalendarDays], ["campaigns", "Campañas", Megaphone], ["templates", "Plantillas", FileText],
  ["audiences", "Audiencias", Users], ["connections", "Conexiones", Link2],
] as const;

const channelLabel: Record<string, string> = { WHATSAPP: "WhatsApp", FACEBOOK: "Facebook", INSTAGRAM: "Instagram" };
const campaignLabel: Record<string, string> = { DRAFT: "Borrador", WAITING_APPROVAL: "Por aprobar", SCHEDULED: "Programada", PROCESSING: "Publicando", PARTIAL: "Resultado parcial", COMPLETE: "Completada", FAILED: "Falló", CANCELLED: "Cancelada" };
const templateLabel: Record<string, string> = { DRAFT: "Borrador", SUBMITTED: "En revisión", APPROVED: "Aprobada", REJECTED: "Rechazada", PAUSED: "Pausada", DISABLED: "Deshabilitada" };

function requestedMonth(value?: string) {
  if (/^\d{4}-(0[1-9]|1[0-2])$/.test(value ?? "")) return value!;
  const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
}

export default async function CommunicationsPage({ searchParams }: { searchParams: Promise<{ view?: string; month?: string; campaignId?: string; servicePlanId?: string }> }) {
  const user = await requirePermission("communications.view");
  const query = await searchParams;
  const view = views.some(([key]) => key === query.view) ? query.view! : "calendar";
  const month = requestedMonth(query.month);
  const canCreate = canAccess(user, "communications.create");
  const canApprove = canAccess(user, "communications.approve");
  const canPublish = canAccess(user, "communications.publish");
  const canConnections = canAccess(user, "communications.connections.manage");
  const canConsent = canAccess(user, "communications.consent.manage");
  const [church, campaignRows, templateRows, audiences, connections, services, people, groupCapability] = await Promise.all([
    prisma.church.findUniqueOrThrow({ where: { id: user.churchId }, select: { name: true, timeZone: true } }),
    prisma.communicationCampaign.findMany({ where: { churchId: user.churchId }, include: { template: true, audience: true, deliveries: { orderBy: { createdAt: "asc" } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.communicationTemplate.findMany({ where: { churchId: user.churchId }, orderBy: { name: "asc" } }),
    prisma.communicationAudience.findMany({ where: { churchId: user.churchId, isActive: true }, orderBy: { name: "asc" } }),
    prisma.socialConnection.findMany({ where: { churchId: user.churchId }, orderBy: { provider: "asc" } }),
    prisma.servicePlan.findMany({ where: { churchId: user.churchId }, select: { id: true, title: true, serviceAt: true }, orderBy: { serviceAt: "desc" }, take: 30 }),
    prisma.person.findMany({ where: { churchId: user.churchId, normalizedPhone: { not: null } }, include: { communicationConsents: { where: { channel: "WHATSAPP" } } }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }], take: 150 }),
    prisma.whatsAppGroupCapability.findUnique({ where: { churchId: user.churchId } }),
  ]);
  const templates = templateRows.map((template) => ({ ...template, channels: stringList(template.channels) as CommunicationChannel[] }));
  const campaigns = campaignRows.map((campaign) => ({ ...campaign, template: campaign.template ? { ...campaign.template, channels: stringList(campaign.template.channels) as CommunicationChannel[] } : null }));
  const selected = campaigns.find((campaign) => campaign.id === query.campaignId);
  const events: CommunicationCalendarEvent[] = campaigns.filter((campaign) => campaign.scheduledAt).map((campaign) => ({ id: campaign.id, title: campaign.title, start: campaign.scheduledAt!.toISOString(), url: `/communications?view=campaigns&campaignId=${campaign.id}`, status: campaign.status, channels: campaign.template?.channels ?? [] }));

  return <>
    <PageHeader title="Comunicaciones" subtitle="Prepara, aprueba y programa anuncios en los canales oficiales de la iglesia." actions={<nav aria-label="Secciones de comunicaciones" className="segmented communication-nav">{views.map(([key, label, Icon]) => <Link aria-current={view === key ? "page" : undefined} className={view === key ? "active" : ""} href={`/communications?view=${key}`} key={key}><Icon />{label}</Link>)}</nav>} />
    <section className="content communications-page">
      {view === "calendar" ? <><div className="section-heading"><div><h2>Calendario editorial</h2><p>Las horas se muestran en {church.timeZone}.</p></div>{canCreate ? <Link className="button primary" href="/communications?view=campaigns#new-campaign"><Megaphone />Nueva campaña</Link> : null}</div><CommunicationsCalendar events={events} month={month} /></> : null}

      {view === "campaigns" ? <div className="communications-split"><div className="campaign-list"><div className="section-heading"><div><h2>Campañas</h2><p>{campaigns.length} campañas registradas</p></div></div>{campaigns.length ? campaigns.map((campaign) => <Link className={`campaign-row ${selected?.id === campaign.id ? "selected" : ""}`} href={`/communications?view=campaigns&campaignId=${campaign.id}`} key={campaign.id}><div><span className={`status-badge communication-${campaign.status.toLowerCase()}`}>{campaignLabel[campaign.status]}</span><strong>{campaign.title}</strong><small>{campaign.template?.channels.map((channel) => channelLabel[channel]).join(" · ") || "Sin canales"}</small></div><time>{campaign.scheduledAt ? formatDate(campaign.scheduledAt, church.timeZone) : "Sin programar"}</time></Link>) : <div className="empty-state"><Megaphone /><p>Aún no hay campañas.</p></div>}</div>
        <div className="campaign-editor">{selected ? <CampaignEditor campaign={selected} audiences={audiences} canApprove={canApprove} canCreate={canCreate} canPublish={canPublish} churchTimeZone={church.timeZone} services={services} /> : canCreate ? <NewCampaign audiences={audiences} defaultServicePlanId={query.servicePlanId} services={services} templates={templates} /> : <div className="empty-state"><CircleAlert /><p>Selecciona una campaña para consultar el detalle.</p></div>}</div></div> : null}

      {view === "templates" ? <div className="management-layout"><div><div className="section-heading"><div><h2>Plantillas</h2><p>WhatsApp solo puede programarse con una plantilla aprobada por Meta.</p></div></div><div className="management-list">{templates.map((template) => <article className="management-row" key={template.id}><div><span className={`status-badge communication-${template.status.toLowerCase()}`}>{templateLabel[template.status]}</span><h3>{template.name}</h3><p>{template.channels.map((channel) => channelLabel[channel]).join(" · ")} · {template.language}</p>{template.rejectionReason ? <p className="danger-text">{template.rejectionReason}</p> : null}</div>{canConnections && template.channels.includes("WHATSAPP") ? <div className="actions">{template.status === "DRAFT" ? <ActionForm action={submitWhatsAppTemplateAction}><input name="templateId" type="hidden" value={template.id} /><button className="button primary" type="submit"><Send />Enviar a Meta</button></ActionForm> : <ActionForm action={syncWhatsAppTemplateAction}><input name="templateId" type="hidden" value={template.id} /><button className="button" type="submit">Sincronizar</button></ActionForm>}</div> : null}</article>)}</div></div>{canCreate ? <TemplateForm /> : null}</div> : null}

      {view === "audiences" ? <div className="communications-stack"><div className="management-layout"><div><div className="section-heading"><div><h2>Audiencias</h2><p>Segmentos reutilizables para campañas.</p></div></div><div className="management-list">{audiences.map((audience) => <article className="management-row" key={audience.id}><div><h3>{audience.name}</h3><p>{audience.description || audienceDescription(audience.criteria)}</p></div></article>)}</div></div>{canCreate ? <AudienceForm services={services} /> : null}</div><div><div className="section-heading"><div><h2>Consentimiento de WhatsApp</h2><p>Solo las personas con alta explícita pueden recibir campañas.</p></div><span className="status-badge">{people.filter((person) => person.communicationConsents[0]?.status === "OPTED_IN").length} autorizados</span></div><div className="consent-table">{people.map((person) => { const consent = person.communicationConsents[0]; return <article className="consent-row" key={person.id}><div><strong>{person.firstName} {person.lastName}</strong><small>{person.phone}</small></div><span className={`status-badge communication-${(consent?.status ?? "PENDING").toLowerCase()}`}>{consent?.status === "OPTED_IN" ? "Autorizado" : consent?.status === "OPTED_OUT" ? "Baja" : "Pendiente"}</span>{canConsent ? <ActionForm action={saveCommunicationConsentAction} className="consent-form"><input name="personId" type="hidden" value={person.id} /><select defaultValue={consent?.status ?? "PENDING"} name="status"><option value="PENDING">Pendiente</option><option value="OPTED_IN">Autorizado</option><option value="OPTED_OUT">Baja</option></select><input defaultValue={consent?.source ?? "Registro administrativo"} maxLength={120} name="source" required /><button className="button" type="submit">Guardar</button></ActionForm> : null}</article>; })}</div></div></div> : null}

      {view === "connections" ? <div className="management-layout"><div><div className="section-heading"><div><h2>Conexiones oficiales</h2><p>Las credenciales se cifran y nunca se muestran después de guardarse.</p></div></div><div className="connection-grid">{connections.map((connection) => <article className="connection-card" key={connection.id}><div className="connection-icon">{connection.status === "CONNECTED" ? <CheckCircle2 /> : <CircleAlert />}</div><div><span>{channelLabel[connection.provider]}</span><h3>{connection.displayName}</h3><p>{connection.status === "CONNECTED" ? "Conexión verificada" : connection.lastError || "Sin verificar"}</p><small>ID: {connection.externalAccountId}</small></div>{canConnections ? <ActionForm action={disconnectSocialConnectionAction} confirmMessage="¿Desconectar esta cuenta y eliminar su token?" successMessage="La cuenta se desconectó."><input name="connectionId" type="hidden" value={connection.id} /><button className="button danger" type="submit">Desconectar</button></ActionForm> : null}</article>)}</div><article className="group-capability"><Radio /><div><h3>Groups API oficial</h3><p>{groupCapability ? `Estado: ${groupCapability.status}` : "Elegibilidad todavía no comprobada."} Los grupos normales no se importan ni reciben mensajes.</p></div></article></div>{canConnections ? <ConnectionForm /> : null}</div> : null}
    </section>
  </>;
}

type Campaign = Awaited<ReturnType<typeof prisma.communicationCampaign.findMany>>[number] & { template: Awaited<ReturnType<typeof prisma.communicationTemplate.findFirst>>; audience: Awaited<ReturnType<typeof prisma.communicationAudience.findFirst>>; deliveries: Array<{ id: string; channel: string; recipientName: string | null; status: string; errorMessage: string | null }> };

function CampaignEditor({ campaign, audiences, services, canCreate, canApprove, canPublish, churchTimeZone }: { campaign: Campaign; audiences: Array<{ id: string; name: string }>; services: Array<{ id: string; title: string; serviceAt: Date }>; canCreate: boolean; canApprove: boolean; canPublish: boolean; churchTimeZone: string }) {
  const content = campaign.content as Record<string, string>;
  return <article className="editor-panel"><div className="section-heading"><div><span className={`status-badge communication-${campaign.status.toLowerCase()}`}>{campaignLabel[campaign.status]}</span><h2>{campaign.title}</h2><p>{campaign.youtubeTitle} · {campaign.youtubeChannel}</p></div><a className="button" href={campaign.sourceUrl} rel="noreferrer" target="_blank">Abrir YouTube</a></div>{campaign.youtubeThumbnailUrl ? <div aria-label={`Miniatura de ${campaign.youtubeTitle}`} className="youtube-preview" role="img" style={{ backgroundImage: `url(${campaign.youtubeThumbnailUrl})` }} /> : null}
    {canCreate && ["DRAFT", "WAITING_APPROVAL", "FAILED"].includes(campaign.status) ? <ActionForm action={updateCampaignContentAction} className="form-grid" successMessage="La campaña se actualizó."><input name="campaignId" type="hidden" value={campaign.id} /><label>Título<input defaultValue={campaign.title} maxLength={160} name="title" required /></label><label>Audiencia<select defaultValue={campaign.audienceId ?? ""} name="audienceId"><option value="">Todas las personas activas con consentimiento</option>{audiences.map((audience) => <option key={audience.id} value={audience.id}>{audience.name}</option>)}</select></label>{stringList(campaign.template?.channels).map((channel) => <label key={channel}>{channelLabel[channel]}<textarea defaultValue={content[channel]} maxLength={channel === "WHATSAPP" ? 1024 : 2200} name={channel} required rows={5} /></label>)}<button className="button" type="submit">Guardar contenido</button></ActionForm> : null}
    {canPublish && ["DRAFT", "WAITING_APPROVAL", "FAILED"].includes(campaign.status) ? <ActionForm action={scheduleCampaignAction} className="schedule-form" successMessage="El horario se guardó."><input name="campaignId" type="hidden" value={campaign.id} /><label>Tipo de horario<select name="scheduleMode"><option value="EXACT">Fecha exacta</option><option value="RELATIVE">Relativo al servicio</option></select></label><label>Fecha<input name="scheduledDate" type="date" /></label><label>Hora<input name="scheduledTime" type="time" /></label><label>Servicio<select defaultValue={campaign.servicePlanId ?? ""} name="servicePlanId"><option value="">Seleccionar</option>{services.map((service) => <option key={service.id} value={service.id}>{service.title} · {formatDate(service.serviceAt, churchTimeZone)}</option>)}</select></label><label>Días relativos<input defaultValue="0" max="30" min="-30" name="relativeDayOffset" type="number" /></label><label>Hora relativa<input name="relativeLocalTime" type="time" /></label><button className="button primary" type="submit">Preparar programación</button></ActionForm> : null}
    {campaign.status === "WAITING_APPROVAL" && canApprove ? <ActionForm action={approveCampaignAction} className="approval-band" confirmMessage="¿Aprobar el contenido actual y activar sus entregas?" successMessage="La campaña quedó aprobada y programada."><input name="campaignId" type="hidden" value={campaign.id} /><div><strong>Aprobación pendiente</strong><p>Versión {campaign.contentVersion}. El envío no comenzará sin autorización.</p></div><button className="button primary" type="submit"><CheckCircle2 />Aprobar</button></ActionForm> : null}
    {campaign.deliveries.length ? <div className="delivery-list"><h3>Entregas</h3>{campaign.deliveries.map((delivery) => <div className="delivery-row" key={delivery.id}><span>{channelLabel[delivery.channel]}</span><strong>{delivery.recipientName || "Cuenta conectada"}</strong><span className={`status-badge communication-${delivery.status.toLowerCase()}`}>{delivery.status}</span>{delivery.errorMessage ? <small>{delivery.errorMessage}</small> : null}</div>)}</div> : null}
    {canPublish && !["COMPLETE", "CANCELLED"].includes(campaign.status) ? <ActionForm action={cancelCampaignAction} confirmMessage="¿Cancelar la campaña y todas sus entregas pendientes?" successMessage="La campaña se canceló."><input name="campaignId" type="hidden" value={campaign.id} /><button className="button danger" type="submit">Cancelar campaña</button></ActionForm> : null}
  </article>;
}

function NewCampaign({ templates, audiences, services, defaultServicePlanId }: { templates: Array<{ id: string; name: string; status: string; channels: string[] }>; audiences: Array<{ id: string; name: string }>; services: Array<{ id: string; title: string; serviceAt: Date }>; defaultServicePlanId?: string }) {
  return <ActionForm action={createCampaignAction} className="editor-panel form-grid" id="new-campaign" successMessage="La campaña se creó."><div><span className="eyebrow">Nueva campaña</span><h2>Compartir un video</h2><p>Pega el enlace público de YouTube y selecciona la preparación inicial.</p></div><label>Enlace de YouTube<input inputMode="url" name="sourceUrl" placeholder="https://www.youtube.com/watch?v=..." required type="url" /></label><label>Título interno<input maxLength={160} name="title" placeholder="Se tomará el título del video si se deja vacío" /></label><label>Plantilla<select name="templateId" required><option value="">Seleccionar</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name} · {template.channels.map((channel) => channelLabel[channel]).join("/")}</option>)}</select></label><label>Audiencia<select name="audienceId"><option value="">Todas las personas activas con consentimiento</option>{audiences.map((audience) => <option key={audience.id} value={audience.id}>{audience.name}</option>)}</select></label><label>Servicio relacionado<select defaultValue={defaultServicePlanId ?? ""} name="servicePlanId"><option value="">Campaña independiente</option>{services.map((service) => <option key={service.id} value={service.id}>{service.title}</option>)}</select></label><button className="button primary" type="submit"><Megaphone />Crear borrador</button></ActionForm>;
}

function TemplateForm() { return <ActionForm action={createCommunicationTemplateAction} className="editor-panel form-grid" successMessage="La plantilla se creó."><div><span className="eyebrow">Nueva plantilla</span><h2>Contenido reutilizable</h2></div><label>Nombre<input maxLength={100} name="name" required /></label><div className="checkbox-row">{["WHATSAPP", "FACEBOOK", "INSTAGRAM"].map((channel) => <label key={channel}><input name="channels" type="checkbox" value={channel} />{channelLabel[channel]}</label>)}</div><label>WhatsApp<textarea defaultValue={"Hola {{person.firstName}}, ya está disponible {{youtube.title}} de {{church.name}}.\n\n{{youtube.url}}"} maxLength={1024} name="WHATSAPP" rows={5} /></label><label>Facebook<textarea defaultValue={"Ya está disponible {{youtube.title}}. Te invitamos a verlo y compartirlo."} maxLength={2200} name="FACEBOOK" rows={4} /></label><label>Instagram<textarea defaultValue={"Ya está disponible {{youtube.title}} de {{church.name}}.\n\n{{youtube.url}}"} maxLength={2200} name="INSTAGRAM" rows={4} /></label><div className="form-columns"><label>Idioma<input defaultValue="es_MX" name="language" required /></label><label>Categoría<select name="category"><option value="MARKETING">Marketing</option><option value="UTILITY">Utilidad</option><option value="AUTHENTICATION">Autenticación</option></select></label></div><label>Nombre remoto opcional<input maxLength={64} name="remoteTemplateName" pattern="[a-z0-9_]+" /></label><label>Publicación<select name="approvalMode"><option value="REQUIRED">Requiere aprobación</option><option value="AUTOMATIC">Automática</option></select></label><button className="button primary" type="submit">Crear plantilla</button></ActionForm>; }

function AudienceForm({ services }: { services: Array<{ id: string; title: string }> }) { return <ActionForm action={createAudienceAction} className="editor-panel form-grid" successMessage="La audiencia se creó."><div><span className="eyebrow">Nueva audiencia</span><h2>Definir segmento</h2></div><label>Nombre<input maxLength={100} name="name" required /></label><label>Descripción<input maxLength={240} name="description" /></label><label>Tipo<select name="type"><option value="ALL_ACTIVE">Todas las personas activas</option><option value="MEMBERS">Miembros activos</option><option value="VISITORS">Visitantes activos</option><option value="TAG">Por etiqueta</option><option value="SERVICE_ATTENDEES">Asistentes de un servicio</option></select></label><label>Etiqueta<input maxLength={80} name="tag" placeholder="Solo para audiencias por etiqueta" /></label><label>Servicio<select name="servicePlanId"><option value="">Solo para asistentes de un servicio</option>{services.map((service) => <option key={service.id} value={service.id}>{service.title}</option>)}</select></label><button className="button primary" type="submit">Crear audiencia</button></ActionForm>; }

function ConnectionForm() { return <ActionForm action={saveSocialConnectionAction} className="editor-panel form-grid" successMessage="La conexión fue verificada."><div><span className="eyebrow">Conectar cuenta</span><h2>Credenciales oficiales</h2><p>Usa un token de usuario de sistema para producción.</p></div><label>Proveedor<select name="provider"><option value="WHATSAPP">WhatsApp Business</option><option value="FACEBOOK">Facebook Page</option><option value="INSTAGRAM">Instagram profesional</option></select></label><label>Nombre visible<input maxLength={120} name="displayName" required /></label><label>WABA, Page o Instagram ID<input maxLength={120} name="externalAccountId" required /></label><label>Phone Number ID<input maxLength={120} name="phoneNumberId" /><small>Obligatorio únicamente para WhatsApp.</small></label><label>Access token<input autoComplete="off" name="accessToken" required type="password" /></label><button className="button primary" type="submit"><Settings2 />Guardar y verificar</button></ActionForm>; }

function formatDate(value: Date, timeZone: string) { return new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "short", timeZone }).format(value); }
function audienceDescription(value: unknown) { const criteria = value as Record<string, unknown>; return criteria.type === "MEMBERS" ? "Miembros activos" : criteria.type === "VISITORS" ? "Visitantes activos" : criteria.type === "TAG" ? `Etiqueta: ${criteria.tag}` : criteria.type === "SERVICE_ATTENDEES" ? "Asistentes de un servicio" : "Todas las personas activas"; }
